update config options in extension.json
alexanderweiss/nova-prettier pull request #120
Opened 2024-12-18 21:41 UTC by stonerl

- Capitalize all titles
- Add keyboard shortcuts to all commands
- Add missing Prettier options
- Add ignore syntax to workspace config
- Update description and links

2024-12-18 21:43 UTC, stonerl commented
I'm going to make the changes bit by bit so it is easier for you to review, I hope. The others will follow as soon as you have approved/merged this one.

2025-02-01 08:46 UTC, alexanderweiss requested changes
Sorry for the massive delay here. This is great! Left a few small notes about some text and I think the `getWorkspaceConfig` function can be kept simpler (see comment).

In addition, I think we should maybe stick to sentence case for the checkbox option titles. That's what Nova's own settings do too. To be honest I think that's why I also somewhat prefer the verb in those options. That's also something Nova's settings has.

2025-02-01 08:46 UTC, alexanderweiss commented on prettier.novaextension/extension.json
> +					"description": "Set a folder for the Prettier module. If not set, it defaults to the build-in Prettier or the module in the project.",
```suggestion
					"description": "Set a folder for the Prettier module. If not set it defaults to Prettier installed in the project, or the built-in Prettier.",
```

I think the order is important as the project Prettier is preferred over the built-in one.

2025-02-01 08:46 UTC, alexanderweiss commented on prettier.novaextension/extension.json
> +			"title": "Prettier Configuration",
I think 'Default' here is pretty useful to have. Since it's ignored in any other case.

2025-02-01 08:46 UTC, alexanderweiss commented on prettier.novaextension/extension.json
> +			"title": "Format on Save Settings",
We're already in the settings pane, so no need for the 'Settings' at the end I'd say

2025-02-01 08:46 UTC, alexanderweiss commented on prettier.novaextension/extension.json
> +					"title": "Format on Saved",
```suggestion
					"title": "Format on Save",
```

2025-02-01 08:46 UTC, alexanderweiss commented on prettier.novaextension/extension.json
> +					"title": "Ignore Without Config",
```suggestion
					"title": "Ignore Documents Without Config",
```

2025-02-01 08:46 UTC, alexanderweiss commented on prettier.novaextension/extension.json
> +							"values": ["Global Default", "Format on Save", "Ignore"],
Nice to use the specific wording! I think it'd be nice to use [the tuple approach described in the docs](https://docs.nova.app/extensions/preferences/#enum-values) so we don't have to have the context-specific handling in `getWorkspaceConfig`

2025-02-15 11:12 UTC, stonerl commented on prettier.novaextension/extension.json
> +			"title": "Prettier Configuration",
The reason why I removed the Default was, that as soon as a user changes the settings here it differs from the prettier default as described on the Prettier homepage.It is  the default only for Nova but not the default behavior of Prettier. I hope you can follow my logic here. But I can re-add `Default` if you want.

2025-02-15 11:18 UTC, stonerl commented
No worries, I know that you don't have much spare time. So I appreciate, that you carved out some of it to review the changes.

Regarding the Sentence case, I'm on the edge here. I have no issues reverting back to it. For the options I just wanted to follow the style that the Prettier project uses. There all Options are Capital Case. But I can change them back to Sentence case if you think it fits better within Nova. Just let me know.

2025-02-15 11:30 UTC, stonerl commented on prettier.novaextension/extension.json
> +							"values": ["Global Default", "Format on Save", "Ignore"],
fixed

2025-03-29 13:23 UTC, stonerl commented
@alexanderweiss I know you're busy, but could you have a look at this, so I can continue addressing your remarks?

2025-03-31 14:22 UTC, closed without merging

2025-03-31 14:36 UTC, alexanderweiss commented
Don't want me to look at it anymore?